# Connection

In [1]:
from google.colab import auth
auth.authenticate_user()

from google.cloud import bigquery

client = bigquery.Client('scaler-sql-476312')

# **CONCAT FUNCTION**

In [2]:
query = """
SELECT *,CONCAT(customer_first_name," ",customer_last_name) as customer_full_name
FROM `scaler-sql-476312.farmers_market.customer`
"""

df = client.query(query).to_dataframe()
df.head()

,customer_id,customer_first_name,customer_last_name,customer_zip,customer_full_name
0,1,Jane,Connor,22801,Jane Connor
1,4,Deanna,Washington,22801,Deanna Washington
2,5,Abigail,Harris,22801,Abigail Harris
3,6,Betty,Bullard,22801,Betty Bullard
4,9,Janet,Forbes,22801,Janet Forbes

# **Using upper() and lower() functions**

In [3]:
query = """
SELECT *,CONCAT(upper(customer_first_name)," ",lower(customer_last_name)) as customer_new_name
FROM `scaler-sql-476312.farmers_market.customer`
"""

df = client.query(query).to_dataframe()
df.head()

,customer_id,customer_first_name,customer_last_name,customer_zip,customer_new_name
0,1,Jane,Connor,22801,JANE connor
1,4,Deanna,Washington,22801,DEANNA washington
2,5,Abigail,Harris,22801,ABIGAIL harris
3,6,Betty,Bullard,22801,BETTY bullard
4,9,Janet,Forbes,22801,JANET forbes

# **Using Substring function**

In [4]:
query = """
SELECT customer_first_name,customer_last_name,CONCAT(substr(customer_first_name,1,1),".",customer_last_name) as customer_full_name
FROM `scaler-sql-476312.farmers_market.customer`
"""

df = client.query(query).to_dataframe()
df.head()

  customer_first_name customer_last_name customer_full_name
0                Jane             Connor           J.Connor
1              Deanna         Washington       D.Washington
2             Abigail             Harris           A.Harris
3               Betty            Bullard          B.Bullard
4               Janet             Forbes           J.Forbes

In [5]:
query = """
SELECT customer_first_name,customer_last_name,CONCAT(lower(substr(customer_first_name,1,1)),upper(substr(customer_first_name,2))," ",lower(substr(customer_last_name,1,1)),
upper(substr(customer_last_name,2))) as name
FROM `scaler-sql-476312.farmers_market.customer`
"""

df = client.query(query).to_dataframe()
df.head()

  customer_first_name customer_last_name               name
0                Jane             Connor        jANE cONNOR
1              Deanna         Washington  dEANNA wASHINGTON
2             Abigail             Harris     aBIGAIL hARRIS
3               Betty            Bullard      bETTY bULLARD
4               Janet             Forbes       jANET fORBES

# **Using SUBSTR() Function by Negative indexing**

In [6]:
query = """
SELECT substr(customer_last_name,-3) from `scaler-sql-476312.farmers_market.customer`
"""

df = client.query(query).to_dataframe()
df.head()

   f0_
0  nor
1  ton
2  ris
3  ard
4  bes

In [7]:
query = """
SELECT substr(customer_last_name,-3,2) from `scaler-sql-476312.farmers_market.customer`
"""

# Here in substr()i mentioned -3 for start and i need only 2 chars so i gave substr(customer_last_name,-3,2)

df = client.query(query).to_dataframe()
df.head()

  f0_
0  no
1  to
2  ri
3  ar
4  be

# Using INITCAP Function

This function only available on BigQuery

In [8]:
query = """
SELECT initcap("sUrYa")
"""

df = client.query(query).to_dataframe()
df.head()

     f0_
0  Surya

# **Where Clause**

**Operators :**
*   AND , OR , NOT
*   Between , In , NOT IN
*   =, != or <>,>,<

In [9]:
#Question: Extract all the product names that are part of product category 1

query = """
SELECT * FROM `scaler-sql-476312.farmers_market.product` WHERE product_category_id = 1

"""

df = client.query(query).to_dataframe()
df

,product_id,product_name,product_size,product_category_id,product_qty_type
0,15,Red Potatoes - Small,,1,Null
1,1,Habanero Peppers - Organic,medium,1,lbs
2,2,Jalapeno Peppers - Organic,small,1,lbs
3,9,Sweet Potatoes,medium,1,lbs
4,13,Baby Salad Lettuce Mix,1 lb,1,lbs
5,17,Carrots,sold by weight,1,lbs
6,22,Roma Tomatoes,medium,1,lbs
7,14,Red Potatoes,None,1,null
8,3,Poblano Peppers - Organic,large,1,unit
9,12,Baby Salad Lettuce Mix - Bag,1/2 lb,1,unit
10,16,Sweet Corn,Ear,1,unit
11,18,Carrots - Organic,bunch,1,unit
12,21,Organic Cherry Tomatoes,pint,1,unit

In [10]:
#Question: Similarly, what if we want all the product names that are part of any other product category except 1?

query = """
SELECT * FROM `scaler-sql-476312.farmers_market.product` WHERE product_category_id != 1

"""

df = client.query(query).to_dataframe()
df

,product_id,product_name,product_size,product_category_id,product_qty_type
0,23,Maple Syrup - Jar,8 oz,2,unit
1,4,Banana Peppers - Jar,8 oz,3,unit
2,5,Whole Wheat Bread,1.5 lbs,3,unit
3,7,Apple Pie,10,3,unit
4,8,Cherry Pie,10,3,unit
5,6,Cut Zinnias Bouquet,medium,5,unit
6,11,Pork Chops,1 lb,6,lbs
7,10,Eggs,1 dozen,6,unit
8,19,Farmer's Market Resuable Shopping Bag,medium,7,unit
9,20,Homemade Beeswax Candles,6,7,unit

In [11]:
# Question: Print a report of everything the customer_id 4 has ever purchased at the market, sorted by date. Add total_amt column as well for each purchase.

query = """
SELECT *, round(quantity * cost_to_customer_per_qty, 2) AS total_amt
FROM `farmers_market.customer_purchases`
WHERE customer_id = 4
ORDER BY market_date
"""
df = client.query(query).to_dataframe()
df

,product_id,vendor_id,market_date,customer_id,quantity,cost_to_customer_per_qty,transaction_time,total_amt
0,4,7,2019-04-03,4,1.00,4.00,18:09:00,4.00
1,4,7,2019-04-10,4,3.00,4.00,17:27:00,12.00
2,4,7,2019-04-10,4,5.00,4.00,16:48:00,20.00
3,4,7,2019-04-13,4,2.00,4.00,10:17:00,8.00
4,4,7,2019-04-17,4,4.00,3.50,18:11:00,14.00
...,...,...,...,...,...,...,...,...
66,3,7,2020-09-05,4,5.00,0.50,11:34:00,2.50
67,1,7,2020-09-09,4,4.14,6.99,17:50:00,28.94
68,2,7,2020-09-12,4,4.22,3.49,12:47:00,14.73
69,2,7,2020-09-26,4,2.73,3.49,10:42:00,9.53
70,1,7,2020-09-26,4,2.96,6.99,10:44:00,20.69

In [12]:
#Question: Get all the product info for products with id between 3 and 8 (not inclusive) and of products with id 10.
query = """
SELECT *
FROM `farmers_market.product`
WHERE product_id > 3 AND product_id < 8 OR product_id = 10
"""
df = client.query(query).to_dataframe()
df

,product_id,product_name,product_size,product_category_id,product_qty_type
0,4,Banana Peppers - Jar,8 oz,3,unit
1,5,Whole Wheat Bread,1.5 lbs,3,unit
2,7,Apple Pie,10,3,unit
3,6,Cut Zinnias Bouquet,medium,5,unit
4,10,Eggs,1 dozen,6,unit

In [13]:
#Question: Find the booth assignments for vendor_id 7 for all dates between April 3, 2019, and May 16, 2019, including the 2 dates.
query = """
SELECT *
FROM `farmers_market.vendor_booth_assignments`
WHERE vendor_id = 7 AND market_date BETWEEN "2019-04-03" AND "2019-05-16"
"""
df = client.query(query).to_dataframe()
df

    vendor_id  booth_number market_date
0           7            11  2019-04-03
1           7            11  2019-04-06
2           7            11  2019-04-10
3           7            11  2019-04-13
4           7            11  2019-04-17
5           7            11  2019-04-20
6           7            11  2019-04-24
7           7            11  2019-04-27
8           7            11  2019-05-01
9           7            11  2019-05-04
10          7            11  2019-05-08
11          7            11  2019-05-11
12          7            11  2019-05-15

In [14]:
# Question - Return a list of customers with the following last names: [Diaz, Edwards, Wilson]
query = """
SELECT *
FROM `farmers_market.customer`
WHERE customer_last_name IN ("Diaz", "Edwards", "Wilson")
"""
df = client.query(query).to_dataframe()
df

   customer_id customer_first_name customer_last_name  customer_zip
0           10             Russell            Edwards         22801
1           17              Carlos               Diaz         22802
2            2              Manuel               Diaz         22821
3            3                 Bob             Wilson         22821

In [15]:
# Same _ Question - Return a list of customers with the following last names: [diaz, edwards, wilson]  Here we don't which case in customer_last_name col
query = """
SELECT *
FROM `farmers_market.customer`
WHERE lower(customer_last_name) IN ("diaz", "edwards", "wilson")
"""
df = client.query(query).to_dataframe()
df

   customer_id customer_first_name customer_last_name  customer_zip
0           10             Russell            Edwards         22801
1           17              Carlos               Diaz         22802
2            2              Manuel               Diaz         22821
3            3                 Bob             Wilson         22821

In [16]:
#Question - Return a list of customers who doesn't have the following last names: [diaz, edwards, wilson]
query = """
SELECT *
FROM `farmers_market.customer`
WHERE lower(customer_last_name) NOT IN ("diaz", "edwards", "wilson")
"""
df = client.query(query).to_dataframe()
df

    customer_id customer_first_name customer_last_name  customer_zip
0             1                Jane             Connor         22801
1             4              Deanna         Washington         22801
2             5             Abigail             Harris         22801
3             6               Betty            Bullard         22801
4             9               Janet             Forbes         22801
5            11             Richard            Paulson         22801
6            14             William              Lopes         22801
7            15             Darrell            Messina         22801
8            16                 Ada             Nieves         22801
9            21               Duane               Sipp         22801
10           22              George                Rai         22801
11           23               Alvin             Laurie         22801
12           24                Dawn               Nale         22801
13           25              Bonnie             Hassan         22801
14           18                Jeri           Mitchell         22802
15           19                 Iva           Kienzler         22802
16           20             Valerie             Loftis         22802
17            7             Jessica            Armenta         22821
18            8               Norma         Valenzuela         22821
19           12                Jack               Wise         22821
20           13              Jeremy             Gruber         22821
21           26              Tracie           Goehring         22821
22           56               Rohit              Menon        110006
23           55               James             Oliver        122067

In [17]:
#Question -- Find out customers who's first name starts with J
query = """
SELECT *
FROM `farmers_market.customer`
WHERE customer_first_name LIKE 'J%'
"""
df = client.query(query).to_dataframe()
df

   customer_id customer_first_name customer_last_name  customer_zip
0            1                Jane             Connor         22801
1            9               Janet             Forbes         22801
2           18                Jeri           Mitchell         22802
3            7             Jessica            Armenta         22821
4           12                Jack               Wise         22821
5           13              Jeremy             Gruber         22821
6           55               James             Oliver        122067

In [18]:
#Question -- Find out customers who's first name ends with e
query = """
SELECT *
FROM `farmers_market.customer`
WHERE lower(customer_first_name) LIKE '%e'
"""
df = client.query(query).to_dataframe()
df

   customer_id customer_first_name customer_last_name  customer_zip
0            1                Jane             Connor         22801
1           21               Duane               Sipp         22801
2           22              George                Rai         22801
3           25              Bonnie             Hassan         22801
4           20             Valerie             Loftis         22802
5           26              Tracie           Goehring         22821

In [19]:
#Question -- Find out customers who's first name starts with j ends with e
query = """
SELECT *
FROM `farmers_market.customer`
WHERE lower(customer_first_name) LIKE 'j%e'
"""
df = client.query(query).to_dataframe()
df

   customer_id customer_first_name customer_last_name  customer_zip
0            1                Jane             Connor         22801

In [20]:
#Question -- Find out customers who's first name second letter with a
query = """
SELECT *
FROM `farmers_market.customer`
WHERE lower(customer_first_name) LIKE '_a%'
"""
df = client.query(query).to_dataframe()
df

   customer_id customer_first_name customer_last_name  customer_zip
0            1                Jane             Connor         22801
1            9               Janet             Forbes         22801
2           15             Darrell            Messina         22801
3           24                Dawn               Nale         22801
4           17              Carlos               Diaz         22802
5           20             Valerie             Loftis         22802
6            2              Manuel               Diaz         22821
7           12                Jack               Wise         22821
8           55               James             Oliver        122067

In [21]:
#Question -- Find out customers who's first name has 'an' in its name
query = """
SELECT *
FROM `farmers_market.customer`
WHERE lower(customer_first_name) LIKE '%an%'
"""
df = client.query(query).to_dataframe()
df

   customer_id customer_first_name customer_last_name  customer_zip
0            1                Jane             Connor         22801
1            4              Deanna         Washington         22801
2            9               Janet             Forbes         22801
3           21               Duane               Sipp         22801
4            2              Manuel               Diaz         22821

In [22]:
#Question -- Find out the uniques product purchased by all customers
query = """
SELECT DISTINCT product_id
FROM `farmers_market.customer_purchases`
"""
df = client.query(query).to_dataframe()
df

   product_id
0           1
1           2
2           3
3           4

In [23]:
#Question -- -- Find out the unique combination product purchased by each customers
query = """
SELECT DISTINCT product_id, customer_id
FROM `farmers_market.customer_purchases`
"""
df = client.query(query).to_dataframe()
df

    product_id  customer_id
0            1           14
1            1           15
2            1           16
3            1           22
4            1            4
..         ...          ...
94           4           10
95           4            8
96           4           18
97           4           17
98           4           15

[99 rows x 2 columns]

In [24]:
#Question --Do we have product with missing (null) product size
query = """
SELECT * FROM `farmers_market.product`
WHERE product_size IS NULL
"""
df = client.query(query).to_dataframe()
df

   product_id  product_name product_size  product_category_id product_qty_type
0          14  Red Potatoes         None                    1             null

In [25]:
#Question --Do we have product which doesn't have (null) product size
query = """
SELECT * FROM `farmers_market.product`
WHERE product_size IS NOT NULL
"""
df = client.query(query).to_dataframe()
df

,product_id,product_name,product_size,product_category_id,product_qty_type
0,15,Red Potatoes - Small,,1,Null
1,1,Habanero Peppers - Organic,medium,1,lbs
2,2,Jalapeno Peppers - Organic,small,1,lbs
3,9,Sweet Potatoes,medium,1,lbs
4,13,Baby Salad Lettuce Mix,1 lb,1,lbs
5,17,Carrots,sold by weight,1,lbs
6,22,Roma Tomatoes,medium,1,lbs
7,3,Poblano Peppers - Organic,large,1,unit
8,12,Baby Salad Lettuce Mix - Bag,1/2 lb,1,unit
9,16,Sweet Corn,Ear,1,unit
10,18,Carrots - Organic,bunch,1,unit
11,21,Organic Cherry Tomatoes,pint,1,unit
12,23,Maple Syrup - Jar,8 oz,2,unit
13,4,Banana Peppers - Jar,8 oz,3,unit
14,5,Whole Wheat Bread,1.5 lbs,3,unit
15,7,Apple Pie,10,3,unit
16,8,Cherry Pie,10,3,unit
17,6,Cut Zinnias Bouquet,medium,5,unit
18,11,Pork Chops,1 lb,6,lbs
19,10,Eggs,1 dozen,6,unit
20,19,Farmer's Market Resuable Shopping Bag,medium,7,unit
21,20,Homemade Beeswax Candles,6,7,unit

In [26]:
#Question --Do we have product which have (blank) product size
query = """
SELECT * FROM `farmers_market.product`
WHERE product_size = " "
"""
df = client.query(query).to_dataframe()
df

,product_id,product_name,product_size,product_category_id,product_qty_type
0,15,Red Potatoes - Small,,1,Null

# Trim Function


Basically it will remove all the blanks and it will act as a null but it is not a null

For Suppose we have a 5 blanks by using trim function it will remove the all the 5 blanks and length will be zero after that it will be  a empty which means no spaces just empty string

In [27]:
#Question -- From Above Question we will remove the blanks for that product by using trim function
query = """
SELECT * FROM `farmers_market.product`
WHERE trim(product_size) = "" or product_size is null
"""
df = client.query(query).to_dataframe()
df

,product_id,product_name,product_size,product_category_id,product_qty_type
0,15,Red Potatoes - Small,,1,Null
1,14,Red Potatoes,None,1,null

In [28]:
#Question -- Replacing null values with unknown and created a cleaned_ps column to store it by using ifnull() function
query = """
SELECT
  product_id,
  product_name,
  product_size, ifnull(product_size, 'unknown') AS cleaned_ps
FROM `farmers_market.product`
"""
df = client.query(query).to_dataframe()
df

,product_id,product_name,product_size,cleaned_ps
0,15,Red Potatoes - Small,,
1,1,Habanero Peppers - Organic,medium,medium
2,2,Jalapeno Peppers - Organic,small,small
3,9,Sweet Potatoes,medium,medium
4,13,Baby Salad Lettuce Mix,1 lb,1 lb
5,17,Carrots,sold by weight,sold by weight
6,22,Roma Tomatoes,medium,medium
7,14,Red Potatoes,None,unknown
8,3,Poblano Peppers - Organic,large,large
9,12,Baby Salad Lettuce Mix - Bag,1/2 lb,1/2 lb
10,16,Sweet Corn,Ear,Ear
11,18,Carrots - Organic,bunch,bunch
12,21,Organic Cherry Tomatoes,pint,pint
13,23,Maple Syrup - Jar,8 oz,8 oz
14,4,Banana Peppers - Jar,8 oz,8 oz
15,5,Whole Wheat Bread,1.5 lbs,1.5 lbs
16,7,Apple Pie,10,10
17,8,Cherry Pie,10,10
18,6,Cut Zinnias Bouquet,medium,medium
19,11,Pork Chops,1 lb,1 lb
20,10,Eggs,1 dozen,1 dozen
21,19,Farmer's Market Resuable Shopping Bag,medium,medium
22,20,Homemade Beeswax Candles,6,6